version: '3'
services:
  apache:
    env_file:
      - .env
    build:
      context: ./apache
      dockerfile: 'pni-apache.Dockerfile'
    networks:
      - proxy
      - default
    volumes:
      - './apache/sites:/usr/local/apache2/conf/sites/:ro'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apachedemo-http.entrypoints=http"
      - "traefik.http.routers.apachedemo-https.entrypoints=https"
      - "traefik.http.routers.apachedemo-https.tls=true"
      - "traefik.http.routers.apachedemo-https.tls.certresolver=letsencrypt-resolver"
      - "traefik.http.routers.apachedemo-http.middlewares=apachedemo-redirectscheme@docker"
      - "traefik.http.routers.apachedemo-http.rule=Host(`${SERVICEHOSTNAME}`)"
      - "traefik.http.routers.apachedemo-https.rule=Host(`${SERVICEHOSTNAME}`)"
      - "traefik.http.middlewares.apachedemo-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.apachedemo-redirectscheme.redirectscheme.permanent=true"
      - "traefik.http.services.apachedemo.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
  flask-root:
    env_file:
      - .env
    build:
      context: ./flask-app
      dockerfile: pythonflask.Dockerfile
    expose:
      - 5000



networks:
  proxy:
    external: true
